/**
 * Canonical permissions and role definitions
 * Source of truth for authorization across the application
 */

export type Permission = string;

export type Role = 'OWNER' | 'ADMIN' | 'DISPATCHER' | 'TECH' | 'CUSTOMER';

export const PERMISSIONS = {
  // System/Admin
  ADMIN_ACCESS: 'admin:access',
  ADMIN_READ: 'admin:read',
  ADMIN_WRITE: 'admin:write',
  // Team
  TEAM_READ: 'team:read',
  TEAM_MANAGE: 'team:manage',
  // Jobs
  JOBS_READ: 'jobs:read',
  JOBS_WRITE: 'jobs:write',
  JOBS_ASSIGN: 'jobs:assign',
  // Clients
  CLIENTS_READ: 'clients:read',
  CLIENTS_WRITE: 'clients:write',
  // Estimates
  ESTIMATES_READ: 'estimates:read',
  ESTIMATES_WRITE: 'estimates:write',
  // Invoices
  INVOICES_READ: 'invoices:read',
  INVOICES_WRITE: 'invoices:write',
  // Billing
  BILLING_READ: 'billing:read',
  BILLING_MANAGE: 'billing:manage',
  // Inbox
  INBOX_READ: 'inbox:read',
  INBOX_WRITE: 'inbox:write',
  // Settings
  SETTINGS_READ: 'settings:read',
  SETTINGS_MANAGE: 'settings:manage',
} as const;

export const ROLE_PERMISSIONS = {
  OWNER: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.ADMIN_READ,
    PERMISSIONS.ADMIN_WRITE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_WRITE,
    PERMISSIONS.JOBS_ASSIGN,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_WRITE,
    PERMISSIONS.ESTIMATES_READ,
    PERMISSIONS.ESTIMATES_WRITE,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_WRITE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  ADMIN: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.ADMIN_READ,
    PERMISSIONS.ADMIN_WRITE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_WRITE,
    PERMISSIONS.JOBS_ASSIGN,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.CLIENTS_WRITE,
    PERMISSIONS.ESTIMATES_READ,
    PERMISSIONS.ESTIMATES_WRITE,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INVOICES_WRITE,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.BILLING_READ,
  ],
  DISPATCHER: [
    PERMISSIONS.ADMIN_ACCESS,
    PERMISSIONS.ADMIN_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_WRITE,
    PERMISSIONS.JOBS_ASSIGN,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
  ],
  TECH: [
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_WRITE,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
  ],
  CUSTOMER: [
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.ESTIMATES_READ,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INBOX_READ,
    PERMISSIONS.INBOX_WRITE,
  ],
};
